# Generated by Django 2.0.3 on 2018-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBCP_MEMBER_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MARKET_INFO', models.CharField(max_length=30)),
                ('PRODUCT_INFO', models.CharField(max_length=30)),
                ('MEMBER_INFO', models.CharField(max_length=30)),
                ('LOGIN_INFO', models.CharField(max_length=30)),
                ('PASSWORD_INFO', models.CharField(max_length=30)),
                ('PERMISSION_INFO', models.CharField(max_length=30)),
                ('OLDPASS_INFO', models.CharField(max_length=30)),
                ('TOKEN_INFO', models.TextField()),
                ('OLDTOKEN_INFO', models.TextField()),
                ('CREATE_INFO', models.DateTimeField(auto_now_add=True)),
                ('UPDATE_INFO', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'tbcp_member_info',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tbcp_member_info',
            unique_together={('MARKET_INFO', 'PRODUCT_INFO', 'MEMBER_INFO')},
        ),
    ]
