# Generated by Django 2.0.3 on 2018-05-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcp_member_info',
            name='OLDPASS_INFO',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tbcp_member_info',
            name='OLDTOKEN_INFO',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tbcp_member_info',
            name='PASSWORD_INFO',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
