# Generated by Django 2.0.3 on 2018-05-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0002_auto_20180508_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcp_member_info',
            name='PASSWORD_INFO',
            field=models.CharField(max_length=30),
        ),
    ]
