# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0004_tbcp_member_list_stat_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBCP_ITEM_META_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ITEM_GROUP', models.CharField(max_length=30)),
                ('ITEM_CODE', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TBCP_MARKET_META_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MARKET_INFO', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TBCP_PRODUCT_META_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_INFO', models.CharField(max_length=30)),
            ],
        ),
    ]
