# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0005_tbcp_item_meta_info_tbcp_market_meta_info_tbcp_product_meta_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcp_member_info',
            name='OLD_DATE_USE',
            field=models.CharField(default='no', max_length=30),
            preserve_default=False,
        ),
    ]
