# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-01 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0006_tbcp_member_info_old_date_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcp_member_list_stat_info',
            name='MEMBER_ASK_CNT',
            field=models.IntegerField(default=0),
        ),
    ]
