# Generated by Django 2.0.3 on 2018-06-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0007_tbcp_member_list_stat_info_member_ask_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBCP_MEMBER_LIST_DETAIL_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MARKET_INFO', models.CharField(max_length=30)),
                ('PRODUCT_INFO', models.CharField(max_length=30)),
                ('MEMBER_INFO', models.CharField(max_length=30)),
                ('TRADE_DATE', models.CharField(max_length=30)),
                ('PROCESS_INFO', models.CharField(max_length=30)),
                ('ITEM_GROUP', models.CharField(max_length=30)),
                ('ITEM_CODE', models.CharField(max_length=30)),
                ('ITEM_SEQ', models.CharField(max_length=30)),
                ('ITEM_DATA', models.CharField(max_length=99999)),
            ],
        ),
    ]
